# Generated by Django 5.0 on 2023-12-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aboutpage_contactpage_homepage_news_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
